### ISSUE TITLE
missed fields at form

### ISSUE THREAD

**Issue by pszemo** [rapidmail/rapidmail-wordpress-plugin#15]
when used shortcode from Wiki
[rm_form show_firstname=1 show_lastname=1 show_gender=1 show_mailtype=1 show_title=1 show_title=1 show_consent_text=1]

on page can see only:
email field and subscribe button

**Comment by eth8505** [comment]
I just tested this with the current version 2.1.4 of the plugin using current wordpress 5.2.2. I cannot reproduce it. Have you actually enabled the fields in the subscription form configuration in rapidmail? Fields will only ever show up in wordpress if they're enabled in rapidmail. Please note that it can take a few minutes for the wordpress plugin to pick up a changed field config.

**Comment by eth8505** [comment]
I still cannot reproduce the issue and there were no updates for two weeks, so I'm closing this.
