### ISSUE TITLE
Add option to show consent checkbox

### ISSUE THREAD

**Issue by silsha** [rapidmail/rapidmail-wordpress-plugin#2]
To use this plugin on German websites, we need an option to display the consent text and checkbox as a required field.

**Comment by eth8505** [comment]
@silsha I have just released a beta version of the next plugin version. We will be testing this internally during the next days and will be fixing any bugs that arise. If you like, you can also test it, i wouldn't recomment installing it on a production system just yet.

The new version imports the form field configuration directly from rapidmail, so all required fields and labels will automatically show up in the wordpress installation. Optional fields can be enabled when adding a widget.

**Comment by eth8505** [comment]
@silsha We just released the 2.1.0 version that allows using the form config directly from rapidmail. When upgrading from an earlier version the new handling needs to be enabled in the rapidmail settings first.

**Comment by silsha** [comment]
@eth8505 💯Thank you! I'll upgrade tomorrow.
